// <auto-generated />
using System;
using DisasterResponseHub.ResourceAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DisasterResponseHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DisasterResponseHub.Models.Donor", b =>
                {
                    b.Property<Guid>("DonorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DonorType")
                        .HasColumnType("int");

                    b.Property<int>("GoodsDonatedGoodDonatedId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DonorID");

                    b.HasIndex("GoodsDonatedGoodDonatedId");

                    b.ToTable("Donor", (string)null);
                });

            modelBuilder.Entity("DisasterResponseHub.Models.GoodsDonated", b =>
                {
                    b.Property<int>("GoodDonatedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodDonatedId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateDonated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DonationCategory")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfItems")
                        .HasColumnType("int");

                    b.HasKey("GoodDonatedId");

                    b.ToTable("GoodsDonated");
                });

            modelBuilder.Entity("DisasterResponseHub.Models.Donor", b =>
                {
                    b.HasOne("DisasterResponseHub.Models.GoodsDonated", "GoodsDonated")
                        .WithMany()
                        .HasForeignKey("GoodsDonatedGoodDonatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsDonated");
                });
#pragma warning restore 612, 618
        }
    }
}
